#pragma once

#include "GeosCli/Commands.hpp"
#include "GeosCli/Command.hpp"

#include "GeosCli/AreaCommand.hpp"
#include "GeosCli/BoundaryCommand.hpp"
#include "GeosCli/BufferCommand.hpp"
#include "GeosCli/CentroidCommand.hpp"
#include "GeosCli/ContainsCommand.hpp"
#include "GeosCli/ConvexHullCommand.hpp"
#include "GeosCli/CountCommand.hpp"
#include "GeosCli/DelaunayTriangulationCommand.hpp"
#include "GeosCli/DistanceCommand.hpp"
#include "GeosCli/EnvelopeCommand.hpp"
#include "GeosCli/InteriorPointCommand.hpp"
#include "GeosCli/IntersectsCommand.hpp"
#include "GeosCli/IsWithinDistanceCommand.hpp"
#include "GeosCli/ListCommand.hpp"
#include "GeosCli/VoronoiDiagramCommand.hpp"
#include "GeosCli/WithinCommand.hpp"