language: cpp

jobs:
  include:

    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - gcc-9
            - g++-9
            - doxygen

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - pip3 install conan
  - mkdir build
  - cd build
  - conan install ../
  - cmake ../
  - cmake --build . -- -j2
  - ctest -j2