language: cpp

jobs:
  include:

    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - gcc-9
            - g++-9
            - doxygen

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-Linux-x86_64.sh
  - chmod +x cmake-3.18.1-Linux-x86_64.sh
  - ./cmake-3.18.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - pip3 install conan
  - mkdir build
  - cd build
  - conan profile update settings.compiler.libcxx=libstdc++11 default 
  - conan install ../
  - cmake ../
  - cmake --build  .
  - ctest --verbose